package com.java.runner;

import com.java.external.*;
import com.java.external.ext1.EveryDay;
import com.java.external.ext2.Ticket;
import com.java.external.ext3.Hand;
import com.java.external.ext5.Voltage;
import com.java.external.ext7.Stem;
import com.java.external.ext8.HandBag;
import com.java.external.ext9.StoryBook;
import com.java.internal.*;
import com.java.internal.int1.*;
import com.java.internal.int2.Destination;
import com.java.internal.int3.SpinalCord;
import com.java.internal.int4.Color;
import com.java.external.ext4.Time;
import com.java.internal.int5.PowerLine;
import com.java.internal.int6.Flow;
import com.java.external.ext6.Dam;
import com.java.external.ext7.Stem;
import com.java.internal.int7.*;
import com.java.internal.int8.*;
import com.java.external.ext8.*;
import com.java.internal.int9.Brand;


public class runner {
    public static void main(String[] args){
        Law law=new Article();
        law.rule();
        System.out.println("------------------------------------------------------");
        Range range=new Network();
        range.jio();
        range.sim();
        System.out.println("-----------------------------------------------------------");
        Laptop laptop=new EveryDay();
        laptop.mobile();
        laptop.battery();
        EveryDay everyDay=new EveryDay();
        everyDay.battery();
        everyDay.mobile();
        Charger charger=new EveryDay();
        charger.mobile();
        System.out.println("------------------------------------------------------------");
        Destination destination=new Ticket();
        destination.lastStop();
        destination.purpleLine();
        destination.yellowLine();
        Ticket ticket=new Ticket();
        ticket.lastStop();
        ticket.yellowLine();
        ticket.purpleLine();
        System.out.println("---------------------------------------------------------------");
        SpinalCord spinal=new Hand();
        spinal.boneMorrow();
        spinal.brain();
        System.out.println("--------------------------------------------------");
        Color color=new Time();
        color.green();
        color.number();
        System.out.println("-------------------------------------------------------");
        PowerLine powerLine=new Voltage();
        powerLine.kb();
        powerLine.current();
        powerLine.wire();
        Voltage voltage=new Voltage();
        voltage.speed();
        voltage.kb();
        voltage.wire();
        voltage.current();
        System.out.println("-------------------------------------------------------------------------------");
       Dam dam =new Dam();
       dam.riverKaveri();
       dam.talaKaveri();
       Flow flow =new Dam();
       flow.talaKaveri();
       flow.riverKaveri();
        System.out.println("-----------------------------------------------------------------------------------");
       Root root= new Stem();
       root.primaryRoot();
       root.flower();
       Stem stem=new Stem();
       stem.flower();
       stem.primaryRoot();
        System.out.println("------------------------------------------------------------------------");
       Bag bag=new HandBag();
       bag.brand();
       bag.price();
       bag.color();
       bag.pouch();
       bag.steel();
       bag.size();
       HandBag handBag=new HandBag();
       handBag.brand();
       handBag.pouch();
       handBag.color();
       handBag.size();
       handBag.steel();
       handBag.price();
       System.out.println("-------------------------------------------------------------");
        StoryBook storyBook=new StoryBook();
        storyBook.classMate();
        storyBook.nataraj();
        storyBook.pages();
        storyBook.ruled();
        storyBook.unRuled();
        storyBook.speed();
        Brand brand=new StoryBook();
        brand.classMate();
        brand.nataraj();
        brand.pages();
        brand.ruled();
        brand.unRuled();
        brand.speed();
        System.out.println("----------------------------------------------------");
        Railway railway=new Source();
        railway.coach();
        railway.flag();
        railway.signal();
        railway.track();
        railway.seat();
        Source source=new Source();
        source.coach();
        source.flag();
        source.signal();
        source.track();
        source.seat();
        System.out.println("-------------------------------------------------");
        Kite kite = new Fly();
        kite.fly();
        kite.thread();
        kite.paper();
        kite.color();
        kite.tail();

        Fly fly = new Fly();
        fly.fly();
        fly.thread();
        fly.paper();
        fly.color();
        fly.tail();
        System.out.println("-------------------------------------------------");

            Shirt shirt = new Wear();
            shirt.collar();
            shirt.sleeve();
            shirt.button();
            shirt.pocket();
            shirt.fabric();

            Wear wear = new Wear();
            wear.collar();
            wear.sleeve();
            wear.button();
            wear.pocket();
            wear.fabric();

            System.out.println("-------------------------------------------------");

            Cupboard cupboard = new Storage();
            cupboard.door();
            cupboard.shelf();
            cupboard.lock();
            cupboard.handle();
            cupboard.material();

            Storage storage = new Storage();
            storage.door();
            storage.shelf();
            storage.lock();
            storage.handle();
            storage.material();

            System.out.println("-------------------------------------------------");
        Doll doll = new Toy();
        doll.hair();
        doll.dress();
        doll.eyes();
        doll.voice();
        doll.size();

        Toy toy = new Toy();
        toy.hair();
        toy.dress();
        toy.eyes();
        toy.voice();
        toy.size();
        System.out.println("-------------------------------------------------");
        Hanger hanger = new Hook();
        hanger.hook();
        hanger.rod();
        hanger.clip();
        hanger.grip();
        hanger.material();

        Hook hook = new Hook();
        hook.hook();
        hook.rod();
        hook.clip();
        hook.grip();
        hook.material();

        System.out.println("-------------------------------------------------");

                IceCream iceCream = new Cone();
                iceCream.flavor();
                iceCream.color();
                iceCream.cone();
                iceCream.size();
                iceCream.price();
                iceCream.toppings();
                iceCream.brand();

                Cone cone = new Cone();
                cone.flavor();
                cone.color();
                cone.cone();
                cone.size();
                cone.price();
                cone.toppings();
                cone.brand();

                System.out.println("-------------------------------------------------");
        Dress dress = new Outfit();
        dress.type();
        dress.color();
        dress.size();
        dress.material();
        dress.design();
        dress.price();
        dress.brand();

        Outfit outfit = new Outfit();
        outfit.type();
        outfit.color();
        outfit.size();
        outfit.material();
        outfit.design();
        outfit.price();
        outfit.brand();

        System.out.println("-------------------------------------------------");
        Lock lock = new Secure();
        lock.key();
        lock.code();
        lock.material();
        lock.size();
        lock.type();
        lock.securityLevel();
        lock.brand();

        Secure secure = new Secure();
        secure.key();
        secure.code();
        secure.material();
        secure.size();
        secure.type();
        secure.securityLevel();
        secure.brand();

        System.out.println("-------------------------------------------------");
        Clip clip = new Pin();
        clip.color();
        clip.size();
        clip.type();
        clip.material();
        clip.grip();
        clip.weight();
        clip.brand();

        Pin pin = new Pin();
        pin.color();
        pin.size();
        pin.type();
        pin.material();
        pin.grip();
        pin.weight();
        pin.brand();

        System.out.println("-------------------------------------------------");
        Bed bed = new Furniture();
        bed.size();
        bed.frame();
        bed.mattress();
        bed.headboard();
        bed.color();
        bed.storage();
        bed.material();

        Furniture furniture = new Furniture();
        furniture.size();
        furniture.frame();
        furniture.mattress();
        furniture.headboard();
        furniture.color();
        furniture.storage();
        furniture.material();

        System.out.println("-------------------------------------------------");
        Aeroplane aeroplane = new Aircraft();
        aeroplane.engine();
        aeroplane.wings();
        aeroplane.passengers();
        aeroplane.fuel();
        aeroplane.altitude();
        aeroplane.speed();
        aeroplane.landingGear();
        aeroplane.cockpit();
        aeroplane.safetyFeatures();

        Aircraft aircraft = new Aircraft();
        aircraft.engine();
        aircraft.wings();
        aircraft.passengers();
        aircraft.fuel();
        aircraft.altitude();
        aircraft.speed();
        aircraft.landingGear();
        aircraft.cockpit();
        aircraft.safetyFeatures();
        System.out.println("-------------------------------------------------");
        Pipe pipe = new Plumbing();
        pipe.diameter();
        pipe.material();
        pipe.length();
        pipe.pressureRating();
        pipe.coating();
        pipe.type();
        pipe.temperatureRating();
        pipe.joints();
        pipe.installationMethod();

        Plumbing plumbing = new Plumbing();
        plumbing.diameter();
        plumbing.material();
        plumbing.length();
        plumbing.pressureRating();
        plumbing.coating();
        plumbing.type();
        plumbing.temperatureRating();
        plumbing.joints();
        plumbing.installationMethod();

        System.out.println("-------------------------------------------------");
        Bricks bricks = new Construction();
        bricks.shape();
        bricks.size();
        bricks.color();
        bricks.weight();
        bricks.material();
        bricks.type();
        bricks.strength();
        bricks.cost();
        bricks.usage();

        Construction construction = new Construction();
        construction.shape();
        construction.size();
        construction.color();
        construction.weight();
        construction.material();
        construction.type();
        construction.strength();
        construction.cost();
        construction.usage();

        System.out.println("----------------------------------------------------------------");
        House house = new Home();
        house.rooms();
        house.doors();
        house.windows();
        house.floors();
        house.roof();
        house.paint();
        house.furniture();
        house.garden();
        house.garage();

        Home home = new Home();
        home.rooms();
        home.doors();
        home.windows();
        home.floors();
        home.roof();
        home.paint();
        home.furniture();
        home.garden();
        home.garage();
        System.out.println("-------------------------------------------------");
        Truck truck = new Transport();
        truck.engine();
        truck.wheels();
        truck.cargoCapacity();
        truck.fuelType();
        truck.axle();
        truck.cabin();
        truck.loadType();
        truck.brand();
        truck.speedLimit();

        Transport transport = new Transport();
        transport.engine();
        transport.wheels();
        transport.cargoCapacity();
        transport.fuelType();
        transport.axle();
        transport.cabin();
        transport.loadType();
        transport.brand();
        transport.speedLimit();
        System.out.println("-----------------------------------------------------------------");


    }
}
